let p1 = [
    {
        id: 1,
        firstname: 'Charlean',
        lastname: 'Winpenny',
        email: 'cwinpenny0@smugmug.com',
        gender: 'Female',
        age: 46,
        city: 'Labrador',
    },
    {
        id: 2,
        firstname: 'Josephine',
        lastname: 'Palay',
        email: 'jpalay1@engadget.com',
        gender: 'Female',
        age: 47,
        city: 'Carrigaline',
    },
    {
        id: 3,
        firstname: 'Bondon',
        lastname: "O'Loughnan",
        email: 'boloughnan2@godaddy.com',
        gender: 'Male',
        age: 39,
        city: 'Zwedru',
    },
    {
        id: 4,
        firstname: 'Poul',
        lastname: 'Adrienne',
        email: 'padrienne3@4shared.com',
        gender: 'Male',
        age: 54,
        city: 'Weitang',
    },
    {
        id: 5,
        firstname: 'Traver',
        lastname: 'Parkyns',
        email: 'tparkyns4@reverbnation.com',
        gender: 'Male',
        age: 40,
        city: 'Gent',
    },
    {
        id: 6,
        firstname: 'Lucas',
        lastname: 'Rikard',
        email: 'lrikard5@nps.gov',
        gender: 'Male',
        age: 53,
        city: 'Sarata',
    },
    {
        id: 7,
        firstname: 'Eugenius',
        lastname: 'Terran',
        email: 'eterran6@delicious.com',
        gender: 'Male',
        age: 40,
        city: 'San Julian',
    },
    {
        id: 8,
        firstname: 'Merrill',
        lastname: 'Vardey',
        email: 'mvardey7@amazon.co.jp',
        gender: 'Female',
        age: 47,
        city: 'Villiers',
    },
    {
        id: 9,
        firstname: 'Darlleen',
        lastname: 'Camoys',
        email: 'dcamoys8@phpbb.com',
        gender: 'Female',
        age: 46,
        city: 'Pyrzyce',
    },
    {
        id: 10,
        firstname: 'Feodora',
        lastname: 'Phillipson',
        email: 'fphillipson9@4shared.com',
        gender: 'Female',
        age: 53,
        city: 'Burgos',
    },
    {
        id: 11,
        firstname: 'Celine',
        lastname: 'Chelam',
        email: 'cchelama@dot.gov',
        gender: 'Female',
        age: 42,
        city: 'Pubu',
    },
    {
        id: 12,
        firstname: 'Ingmar',
        lastname: 'Agglio',
        email: 'iaggliob@usgs.gov',
        gender: 'Male',
        age: 42,
        city: 'Kristiansand S',
    },
    {
        id: 13,
        firstname: 'Vere',
        lastname: 'Yakobovitz',
        email: 'vyakobovitzc@blogs.com',
        gender: 'Female',
        age: 51,
        city: 'Stockholm',
    },
    {
        id: 14,
        firstname: 'Ashely',
        lastname: 'Rappport',
        email: 'arappportd@sbwire.com',
        gender: 'Female',
        age: 48,
        city: 'Krajan Pakel',
    },
    {
        id: 15,
        firstname: 'Sky',
        lastname: 'Bellhouse',
        email: 'sbellhousee@rediff.com',
        gender: 'Male',
        age: 45,
        city: 'Lidong',
    },
    {
        id: 16,
        firstname: 'Yehudit',
        lastname: 'Bemand',
        email: 'ybemandf@ft.com',
        gender: 'Male',
        age: 48,
        city: 'Solna',
    },
    {
        id: 17,
        firstname: 'Shane',
        lastname: 'Whitesel',
        email: 'swhiteselg@lulu.com',
        gender: 'Female',
        age: 40,
        city: 'Donan',
    },
    {
        id: 18,
        firstname: 'Bear',
        lastname: 'Higbin',
        email: 'bhigbinh@reverbnation.com',
        gender: 'Male',
        age: 34,
        city: 'Nam Kliang',
    },
    {
        id: 19,
        firstname: 'Fransisco',
        lastname: 'Colclough',
        email: 'fcolcloughi@is.gd',
        gender: 'Male',
        age: 53,
        city: 'Motala',
    },
    {
        id: 20,
        firstname: 'Robin',
        lastname: 'Runnicles',
        email: 'rrunniclesj@bravesites.com',
        gender: 'Female',
        age: 53,
        city: 'Proboštov',
    },
];

// whatever the variable "p1" represents is exported to outside of
// this module as "people"
// By default module.exports is equals to {}
module.exports['people'] = p1;
// after the above statement, module.exports is {people: [...]}
